version: '3'

tasks:
  
  generate:
    cmds:
      - task: generate_ts

  serve:
    cmds:
      - go run ./cmd/server
    deps:
      - build_webui
      - copy_html
  
  build_webui:
    cmds:
      - yarn build
    sources:
      - ./internal/webui/**/*.*
    generates:
      - ./internal/router/dist/bundle.html
      - ./internal/router/dist/bundle.js
      - ./internal/router/dist/bundle.css
  
  copy_html:
    cmds:
      - mkdir -p ./internal/router/dist
      - cp ./internal/webui/index.html ./internal/router/dist/bundle.html
    sources:
      - ./internal/webui/index.html
    generates:
      - ./internal/router/dist/bundle.html

  test:
    cmds:
      - go test -v ./...

  generate_ts:
    cmds:
      - go run ./cmd/gents -o internal/generated/types.ts
    sources:
      - internal/models/*.go
    generates:
      - internal/generated/types.ts

